### ISSUE TITLE
unexpected symbol near "<"

### ISSUE THREAD

**Issue by TheLuaFox86** [JorjBauer/lua-6502#2]
line 13: 6502.lua unexpected symbol near "<"
what do i do
im trying to run it on ish app on ipad os
it mimiks the alpine linux enviorment

**Comment by JorjBauer** [comment]
Sounds like you're using an old version of Lua. This requires at least Lua 5.3.

**Comment by NotAuser999** [comment]
thanks

**Comment by NotAuser999** [comment]
sorry offline for too long btw it helped but im using ish on ipad pro but cant seem to get it to work
